In [1]:
# 1. nothing to do

In [2]:
# 2. Print the julia version
VERSION

v"1.7.3"

In [3]:
# 3. Create a null vector of size 10
Z = zeros(10)

10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [4]:
# 4. Create a null vector of size 10 but the fifth value which is 1
Z = zeros(10)
Z[5] = 1.0
Z

10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [5]:
# 5. Create a vector with values ranging from 10 to 99
Z = (10:99)

10:99

In [6]:
# 6. Create a 3x3 matrix with values ranging from 0 to 8
Z = reshape(0:8, 3, 3)

3×3 reshape(::UnitRange{Int64}, 3, 3) with eltype Int64:
 0  3  6
 1  4  7
 2  5  8

In [7]:
# 7. Find indices of non-zero elements from [1,2,0,0,4,0]
using SparseArrays
nz = sparse([1,2,0,0,4,0])

6-element SparseVector{Int64, Int64} with 3 stored entries:
  [1]  =  1
  [2]  =  2
  [5]  =  4

In [8]:
# 8. Create a 3x3 identity matrix
using LinearAlgebra
Z = Matrix{Float64}(I,3,3)

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [9]:
# 9. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
using LinearAlgebra
Z =  diagm(-1 => (1:4))
#Z = diagm(-1 => (1,2,3,4))

5×5 Matrix{Int64}:
 0  0  0  0  0
 1  0  0  0  0
 0  2  0  0  0
 0  0  3  0  0
 0  0  0  4  0

In [10]:
# 10. Create a 10x10x10 array with random values
rand(10,10,10)

10×10×10 Array{Float64, 3}:
[:, :, 1] =
 0.383954    0.139089   0.948569   0.423947  …  0.868452  0.204185  0.113187
 0.874365    0.103637   0.466148   0.378257     0.619348  0.625604  0.474342
 0.845302    0.0735393  0.0951557  0.311952     0.447392  0.283516  0.95337
 0.370087    0.454346   0.29567    0.369013     0.192923  0.390714  0.580195
 0.916299    0.652096   0.510759   0.991159     0.958644  0.823919  0.48201
 0.404025    0.467858   0.514325   0.933971  …  0.570084  0.409177  0.298545
 0.0289369   0.37486    0.721031   0.903042     0.211362  0.047046  0.429393
 0.00254656  0.333444   0.234211   0.690091     0.569195  0.887746  0.660727
 0.985946    0.677698   0.985718   0.67579      0.939295  0.384067  0.894366
 0.706749    0.584949   0.229072   0.532977     0.709196  0.113982  0.705997

[:, :, 2] =
 0.0302165  0.00641257  0.497477   …  0.914127   0.0721614  0.389311
 0.0589024  0.859724    0.932807      0.553349   0.836826   0.855245
 0.423056   0.851911    0.52893       0.5