In [1]:
# 11. Create a 8x8 matrix and fill it with a checkerboard pattern
[(i+j)%2 for i=1:8, j=1:8]

8×8 Matrix{Int64}:
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0

In [2]:
# 12. Create a 10x10 array with random values and find the minimum and maximum values
Z = rand(10,10)
Zmin,Zmax = minimum(Z),maximum(Z)
#Zmin,Zmax = extrema(Z)

(0.003447284724326538, 0.978018457993763)

In [3]:
# 13. Create a checkerboard 8x8 matrix using the tile function
#　分かりません

In [4]:
# 14. Normalize a 5x5 random matrix (between 0 and 1)
Z = rand(5,5)
Zmin,Zmax = extrema(Z)
Z = (Z .- Zmin)/(Zmax - Zmin)
#.(ドット)は各成分への作用を意味する

5×5 Matrix{Float64}:
 0.697214  0.770536  0.257528  0.750659   0.984469
 0.14183   0.46543   0.811568  0.715038   0.703007
 0.88224   0.132961  0.611589  0.703277   0.811709
 0.0       1.0       0.741108  0.753918   0.702692
 0.200524  0.621183  0.934656  0.0251492  0.493395

In [5]:
# 15. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
Z = ones(5,3) * ones(3,2)

5×2 Matrix{Float64}:
 3.0  3.0
 3.0  3.0
 3.0  3.0
 3.0  3.0
 3.0  3.0

In [6]:
# 6. Create a 10x10 matrix with row values ranging from 0 to 9
[j-1 for i=1:10,j=1:10]

10×10 Matrix{Int64}:
 0  1  2  3  4  5  6  7  8  9
 0  1  2  3  4  5  6  7  8  9
 0  1  2  3  4  5  6  7  8  9
 0  1  2  3  4  5  6  7  8  9
 0  1  2  3  4  5  6  7  8  9
 0  1  2  3  4  5  6  7  8  9
 0  1  2  3  4  5  6  7  8  9
 0  1  2  3  4  5  6  7  8  9
 0  1  2  3  4  5  6  7  8  9
 0  1  2  3  4  5  6  7  8  9

In [7]:
# 7. Create a vector of size 1000 with values ranging from 0 to 1, both excluded
Z = range(0,1,1002)[2:end-1]
#range(initial,end,number)でベクトルを作り、[2:end-1]で端を取り除く

0.000999000999000999:0.000999000999000999:0.999000999000999

In [8]:
# 8. Create a random vector of size 100 and sort it
Z = rand(100)
sort(Z) 
#Zをソートしたものに置き換えたい場合はsort!(Z)をする

100-element Vector{Float64}:
 0.0028020794446287356
 0.02927982641316662
 0.03395390914457053
 0.039339404041947246
 0.04437937932058167
 0.06887367906754793
 0.07435725945469296
 0.0909603567509667
 0.1037627278151505
 0.12725990040452806
 0.13068800010497705
 0.13971937546691127
 0.14164104072821415
 ⋮
 0.8931267567585622
 0.9003277020547344
 0.9018144304125552
 0.9136681658798207
 0.9169515685486068
 0.9251604950833839
 0.9325961531470838
 0.9385244429699154
 0.9403737798349858
 0.9443041596393079
 0.9642889428708629
 0.9745950472253545

In [9]:
# 9. Consider two random matrices A anb B, check if they are equal.
A,B = rand(10)
A == B

false

In [10]:
using Statistics
# 10. Create a random vector of size 1000 and find the mean value
Z = rand(1000)
m = mean(Z)

0.4796864154341705